### ISSUE TITLE
crash when sending a struct

### ISSUE THREAD

**Issue by neuraldude** [kirankunigiri/peertalk-simple#2]
I'm encountering a crash when sending a two-dimensional array wrapped up in a struct. So this works for me: 

```
// sending
var Traj: [[Int]] =  ....
ptManager.sendObject(object: Traj, type: PTType.number.rawValue)

 // receiving
 let Traj = data.convert() as! [[Int]]

```
but when I attempt to do

```
// sending
struct Trial{
    let header: String
    let payload: [[Int]]
}
let trial = Trial(header: "hello", payload: Traj)
 ptManager.sendObject(object: trial, type: PTType.number.rawValue)

// receiving
struct Trial{
    let header: String
    let payload: [[Int]]
}    
let trial = data.convert() as! Trial

```
I get a crash when sending. Am I doing something wrong, or is there a bug?

**Comment by robinspeijer** [comment]
As mentioned by the readme, sendObject() tries to encode a given object into data using NSKeyedArchiver. Since a struct is not an object and doesn't conform to NSCoding, this will obviously fail. You should be able to convert the struct to data yourself and send it using sendData().

**Comment by kirankunigiri** [comment]
@robinspeijer, thanks for helping out!
