### ISSUE TITLE
Not working with App Sandbox Enable

### ISSUE THREAD

**Issue by miteshkhatri** [kirankunigiri/peertalk-simple#3]
I developed a OSX application that listening the USB devices that connected from OSX and application runs fine before submit to app store. At the time of submission to app store I enabled the "App Sandbox" and enabled USB in App Sandbox. But after enable this application is not able to get the list of USB connected devices. 

So now please  suggest the solution for this. or suggest any option to get the devices list which is connected from osx using USB.

**Comment by kirankunigiri** [comment]
Unfortunately, I was not able to figure out a solution for this. I will add this problem to the README asap. I ended up releasing my app on a website instead of the app store.

**Comment by miteshkhatri** [comment]
Thanks for sharing info.
