### ISSUE TITLE
Computer and iOS Device not connecting even though "Connected: true" shows up in logs

### ISSUE THREAD

**Issue by Ash-Ranjan** [kirankunigiri/peertalk-simple#8]
I am trying to send some data using Peertalk Simple example project though the devices are not connecting. When I run the program "Connected: true" shows up in both of their logs when they should be connected and "Connected: false" shows up when they are not, but in both cases, none of the other connection code is executed and I am unable to send messages, I have checked and the value for peerChanel is both are nil, I have copied the connection code from the example project and do not know what is wrong, any help would be appreciated.

**Comment by PaperMashe** [comment]
Sorry, unfortunately, I won't help you as I am too struggling with getting it to work. May I ask, did you build the example projects as they were? What did you do when adding the code into your project exactly, what files did you copy over? Did it give any errors, if so what were they? What version of Xcode do you have? what version of swift are you using? also... I am not sure if there will be any help coming any time soon as the last reply was a long time ago, I myself was just asking some questions here a couple of days ago but no response yet.

**Comment by Ash-Ranjan** [comment]
I used the example project and made a few modifications to the PTTypes and the functions that pick the image or add to the counter, but I have not changed the other code, I am currently working on seeing if I am missing something.

**Comment by Ash-Ranjan** [comment]
Turns out I was writing in Manual View Controller instead of Simple View Controller. That was the problem
